version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: spring-boot-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: spring_boot_mongo
      TZ: UTC
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: